version: "3.8"
services:
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      # Mount your static files or custom config if needed
      - ./public-html/${SERVICE_UNDER_MAINTENANCE}:/usr/local/apache2/htdocs
      # - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: unless-stopped
